In [15]:
# Import models
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.datasets import load_iris
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,accuracy_score

In [16]:
# read dataset
iris=pd.read_csv("iris.csv")
print("Dataset : \n",iris)

Dataset : 
      sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2      Iris-setos
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]


In [17]:
#applying label encoding
label_encoder =LabelEncoder()
iris['species']= label_encoder.fit_transform(iris['species'])


In [18]:
# Distinguish dependent and independent variables
x=iris.iloc[:,:3]
y=iris.iloc[:,-1]

print("Independent variables are : \n",x)
print("Dependent variables are : \n",y)

Independent variables are : 
      sepal_length  sepal_width  petal_length
0             5.1          3.5           1.4
1             4.9          3.0           1.4
2             4.7          3.2           1.3
3             4.6          3.1           1.5
4             5.0          3.6           1.4
..            ...          ...           ...
145           6.7          3.0           5.2
146           6.3          2.5           5.0
147           6.5          3.0           5.2
148           6.2          3.4           5.4
149           5.9          3.0           5.1

[150 rows x 3 columns]
Dependent variables are : 
 0      1
1      1
2      1
3      1
4      0
      ..
145    3
146    3
147    3
148    3
149    3
Name: species, Length: 150, dtype: int32


In [19]:
# split test and training data
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4,random_state=4)

In [20]:
#SVC model
sv=SVC(kernel="linear",random_state=42)
model=sv.fit(x_train,y_train)
y_pred=model.predict(x_test)


In [21]:
print("Confusion matrix : \n",confusion_matrix(y_pred,y_test))
print("Accuracy : ",accuracy_score(y_pred,y_test))

Confusion matrix : 
 [[25  0  0]
 [ 0 16  0]
 [ 0  1 18]]
Accuracy :  0.9833333333333333
